mark: ""

model_path: "stabilityai/stable-diffusion-2-1"

gpu: 2

# feature injection setting
start_step: 0
inject_step: 20
end_step: 50
layer_idx: [10,11,12,13,14,15]


# set seeds
seeds: [253019]

# set reference image infos
ref_image_infos: {
  dataset/Ukiyo-e/image/girl.jpg: a girl in Ukiyo-e style,
  dataset/Ukiyo-e/image/wave.jpg: wave in Ukiyo-e style
  }

target_prompt: "a girl with wave in Ukiyo-e style"

ref_index: [2,4]

# weaken the irrelevant token‘s attention during semantic segmentation. 
# 0.9 is advised for single-concept generation, while 0.6 is better suited for multi-concept generation
ca_scale: 0.5

# ref image setting
use_null_ref_prompts: False     # Whether or not to use an empty prompt when denoising reference images.
mask_weights: [3.0, 2.0]   # The larger the mask_weight is, the higher attention is for the reference image.

negative_prompt: "lowres, bad anatomy, text, error, cropped, worst quality, low quality, normal quality, jpeg artifacts, blurry, freak, disharmony, ugly, horrible, disabled body, naked"