mark: ""

model_path: "stabilityai/stable-diffusion-2-1-base"

gpu: 2

# feature injection setting
start_step: 0
inject_step: 20
end_step: 50
layer_idx: [10,11,12,13,14,15]


# set seeds
seeds: [430375]

# set reference image infos
ref_image_infos: {
  dataset/Vintage_Films/image/woman.jpg: a woman,
  dataset/Vintage_Films/image/clothes.jpg: a woman,
  dataset/Vintage_Films/image/hair.jpg: a woman,
  }

target_prompt: "a woman with short hair wearing a clothes"

ref_index: [2,8,5]

# weaken the irrelevant token‘s attention during semantic segmentation. 
# 0.9 is advised for single-concept generation, while 0.6 is better suited for multi-concept generation
ca_scale: 0.6

# ref image setting
use_null_ref_prompts: False     # Whether or not to use an empty prompt when denoising reference images.
mask_weights: [2.5, 2.0, 2.5]   # The larger the mask_weight is, the higher attention is for the reference image.

negative_prompt: "lowres, bad anatomy, text, error, cropped, worst quality, low quality, normal quality, jpeg artifacts, blurry, freak, disharmony, ugly, horrible, disabled body, naked"
