mark: ""

model_path: "stabilityai/stable-diffusion-2-1-base"

gpu: 2


# feature injection setting
start_step: 0
inject_step: 20
end_step: 50
layer_idx: [10,11,12,13,14,15]


# set seeds
seeds: [303583]

# set reference image infos
ref_image_infos: {
  dataset/Painting/image/woman.jpg: a painting of a woman,
  dataset/Painting/image/flowers.jpg: a painting of a woman holding flowers
  }

target_prompt: "a painting of a woman with flowers in hair"

ref_index: [5, 7]

# weaken the irrelevant token‘s attention during semantic segmentation. 
# 0.9 is advised for single-concept generation, while 0.6 is better suited for multi-concept generation
ca_scale: 0.6 

# ref image setting
use_null_ref_prompts: False     # Whether or not to use an empty prompt when denoising reference images.
mask_weights: [4.0, 3.0]   # The larger the mask_weight is, the higher attention is for the reference image.

negative_prompt: "lowres, bad anatomy, text, error, cropped, worst quality, low quality, normal quality, jpeg artifacts, blurry, freak, disharmony, ugly, horrible, disabled body, naked"
